### ISSUE TITLE
Bios

### ISSUE THREAD

**Issue by Trosscam** [devhunterco/devhunter-app#10]
Error en la bios, se sobrepone el texto, al poseer una Bios y editarla se sobrepone sobre el texto anterior.

**Comment by juliocesar-io** [comment]
Efectivamente se ropia la linea de texto y se superponia, eso por que tenia un  `line-height al 30%`, fue correjido en el commit [5d27a0e](https://github.com/devhunterco/devhunter-app/commit/5d27a0e0e5dbd709989fece3a9d07fd216ff77a5).
