### ISSUE TITLE
Recuperación de contraseñas

### ISSUE THREAD

**Issue by carlosjs23** [devhunterco/devhunter-app#11]
Dice que se ha enviado la contraseña aun si el correo ingresado no corresponde a ningún usuario de la base de datos.

**Comment by juliocesar-io** [comment]
Revisando :+1:

**Comment by juliocesar-io** [comment]
Ya se valida que exista un usuario con la dirección de correo proporcionada. Véase [4b9b649](https://github.com/devhunterco/devhunt/commit/4b9b6498c707b1d6d99a68d4a85eea78bcf62393)

**Comment by carlosjs23** [comment]
Buen trabajo Julio :+1:
