### ISSUE TITLE
Perfil publico

### ISSUE THREAD

**Issue by carlosjs23** [devhunterco/devhunter-app#12]
Los perfiles de usuarios siempre deben ser públicos y no privados como ocurre en nuestro sitio.

**Comment by juliocesar-io** [comment]
Ya se resolvió en el commit [b5298e5](https://github.com/devhunterco/devhunt/commit/b5298e5c1e6fdc1f1c5ad25cdd85ce1aaaabdcd6).

**Comment by carlosjs23** [comment]
muy bien.
