### ISSUE TITLE
Problema en el pie de página.

### ISSUE THREAD

**Issue by carlosjs23** [devhunterco/devhunter-app#15]
Ocurre cuando visitas una discusión, navegador: Chromium - Firefox.
![snapshot1](https://cloud.githubusercontent.com/assets/10473519/9745511/e9cb2fba-5637-11e5-96ee-50fca432e4b6.png)

**Comment by juliocesar-io** [comment]
Listo. Lindo KDE :smile:

**Comment by ivajo26** [comment]
Yo pensé que como habías dicho listo, ya lo habías solucionado
