### ISSUE TITLE
Actividades pasadas orden inverso.

### ISSUE THREAD

**Issue by carlosjs23** [devhunterco/devhunter-app#16]
Quedaría mejor si se muestran las mas recientes primero.

![instantanea1](https://cloud.githubusercontent.com/assets/10473519/9978431/90596e1e-5ef3-11e5-809b-6f9a21654df3.png)

**Comment by juliocesar-io** [comment]
Se supone que estaba de esa forma. Hay que revisar el query.

**Comment by ivajo26** [comment]
Eso se cambio en la ultima edición que hicisteis

**Comment by ivajo26** [comment]
Revise y esta bien, eso esta bien trol Jajaja

**Comment by carlosjs23** [comment]
#closerequest
