### ISSUE TITLE
Formateo de Markdown en Últimos Comentarios.

### ISSUE THREAD

**Issue by carlosjs23** [devhunterco/devhunter-app#18]
Si se dan cuenta, la sección de Últimos Comentarios ubicada en la página principal, no se está formateando en Markdown, sino que muestra el markdown como texto plano.

:fast_forward:

**Comment by ivajo26** [comment]
Muchas gracias se ha corregido con el [Commit](https://github.com/devhunterco/devhunt/commit/db1a672ce00af67df4341f42c7e17dac9ef9f595)
