### ISSUE TITLE
Error al subir imagenes

### ISSUE THREAD

**Issue by ivajo26** [devhunterco/devhunter-app#3]
Cuando se intenta ingresar un comentario y agregarle una imagen, al momento de seleccionarla del ordenar, se arroja este error **_![error: error INTERNAL SERVER ERROR]()**_ , y no carga la imagen
![captura de pantalla de 2015-02-21 22 37 26](https://cloud.githubusercontent.com/assets/6981217/6317320/3b29c4ee-ba1a-11e4-9322-31db1e1fd482.png)

**Comment by juliocesar-io** [comment]
Resolvido, era un problema de permisos en el S.O con los folders.

Simplemente: 

`sudo chgrp -R varwwwusers carpeta/de/media`
`sudo chmod -R 770 carpeta/de/media` 

`varwwwusers` es el grupo al pertenece el "usuario"  bajo el que opera el backend.
